# Generated by Django 5.0.6 on 2024-05-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='pre_report',
            field=models.TextField(blank=True, default=''),
        ),
    ]
