# Generated by Django 5.0.6 on 2024-05-13 15:13

import goal.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0003_alter_match_pre_report_alter_match_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='pre_report',
            field=goal.models.MarkdownHTMLField(blank=True, default='', validators=[goal.models.validate_html, goal.models.validate_html]),
        ),
        migrations.AlterField(
            model_name='match',
            name='report',
            field=goal.models.MarkdownHTMLField(blank=True, default='', validators=[goal.models.validate_html, goal.models.validate_html]),
        ),
    ]
